///////////////////////////////////////////////////////////
//  NonPlayerCharacter.cs
//  Implementation of the Class NonPlayerCharacter
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:37 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////

using System;

namespace Mazegame.Entity
{
    public class NonPlayerCharacter : Character
    {
        private Boolean hostile;
        private Location currentLocation;
        public NonPlayerCharacter(String name):base(name)
        {
        }

        public Location CurrentLocation
        {
            get { return currentLocation; }
            set { currentLocation = value; }
        }
        public Boolean Hostile
        {
            get { return hostile; }
            set { hostile = value; }
        }
    } //end NonPlayerCharacter
} //end namespace Entity